import type { BuildInfo } from '../src/shared/provenance.ts';

/** The GitHub Actions run URL from the variables Actions sets; null outside Actions. */
export function maybeCiRunUrl(env: Readonly<Record<string, string | undefined>>): string | null {
    const { GITHUB_SERVER_URL: maybeServer, GITHUB_REPOSITORY: maybeRepository, GITHUB_RUN_ID: maybeRunId } = env;
    if (!maybeServer || !maybeRepository || !maybeRunId) {
        return null;
    }
    return `${maybeServer}/${maybeRepository}/actions/runs/${maybeRunId}`;
}

/** The source of `src/js/buildInfo.ts` for `info`. */
export function buildInfoModule(info: BuildInfo): string {
    return `// Generated by scripts/generateBuildInfo.ts. Do not edit.
import type { BuildInfo } from '../shared/provenance';

export const BUILD_INFO: BuildInfo = ${JSON.stringify(info, null, 4)};
`;
}
