/**
 * Apple accepts at most three period-separated integers as an app version,
 * while browser extension manifests allow four.
 */
const APPLE_VERSION_PATTERN = /^\d+(\.\d+){0,2}$/;

/**
 * Builds the Xcode configuration that gives the Safari app the extension's
 * manifest version, so the version is only ever bumped in `src/manifest.json`.
 *
 * @throws if `manifestVersion` is not a version the App Store accepts.
 */
export function safariVersionXcconfig(manifestVersion: string): string {
    if (!APPLE_VERSION_PATTERN.test(manifestVersion)) {
        throw new Error(`Manifest version "${manifestVersion}" is not valid for the App Store: use one to three period-separated integers.`);
    }
    return `// Generated by scripts/generateBuildInfo.ts from src/manifest.json. Do not edit.
MARKETING_VERSION = ${manifestVersion}
CURRENT_PROJECT_VERSION = ${manifestVersion}
`;
}
